package logic

enum class TaskOperation { ADD_LEADER, ADD_MEMBER, ADD_TASK, REMOVE_TASK, CHANGE_TASK_STATUS, ERROR_REMOVING_TASK, ERROR_CHANGING_STATUS }

enum class Status { RUNNING, SUSPENDED, MONITORING, FINISHED, ELIMINATED, EMPTY }